modLoader="javafml"
loaderVersion="[63,)"
license="MIT"
[[mods]]
modId="thetruepaxels"
version="1.1.2"
displayName="The True Paxels"
authors="JustErikSK, Satorisek, With Rage Studios"
description='''Mine everything with one tool! Paxels are universal tools that work like pickaxes, axes and shovels - all at the same time!'''
[[dependencies.thetruepaxels]]
    modId="forge"
    mandatory=true
    versionRange="[63,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.thetruepaxels]]
    modId="minecraft"
    mandatory=true
    versionRange="[26.1.1,26.2,)"
    ordering="NONE"
    side="BOTH"
